#
# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#

from livetypes import LanguageMetadata, LanguageModel

MODELS_LIST = {
	"ar": "vosk-model-ar-mgb2-0.4",
	"ar_TN": "vosk-model-small-ar-tn-0.1-linto",
	"br": "vosk-model-br-0.8",
	"ca": "vosk-model-small-ca-0.4",
	"cs": "vosk-model-small-cs-0.4-rhasspy",
	"de": "vosk-model-small-de-0.15",
	"en": "vosk-model-en-us-0.22",
	"eo": "vosk-model-small-eo-0.42",
	"es": "vosk-model-small-es-0.42",
	"fa": "vosk-model-small-fa-0.42",
	"fr": "vosk-model-small-fr-0.22",
	"hi": "vosk-model-small-hi-0.22",
	"it": "vosk-model-small-it-0.22",
	"ja": "vosk-model-small-ja-0.22",
	"kk": "vosk-model-small-kz-0.15",
	"ko": "vosk-model-small-ko-0.22",
	"nl": "vosk-model-small-nl-0.22",
	"pl": "vosk-model-small-pl-0.22",
	"pt": "vosk-model-small-pt-0.3",
	"ru": "vosk-model-small-ru-0.22",
	"te": "vosk-model-small-te-0.42",
	"tg": "vosk-model-small-tg-0.22",
	"tr": "vosk-model-small-tr-0.3",
	"uk": "vosk-model-small-uk-v3-nano",
	"uz": "vosk-model-small-uz-0.22",
	"vi": "vosk-model-small-vn-0.4",
	"zh": "vosk-model-small-cn-0.22",
}


# all languages
# many languages might be missing/have incorrect metadata, they can be added/fixed as needed
LANGUAGE_MAP = {
	"aa": LanguageModel(name="Afar"),
	"abt": LanguageModel(name="Ambulas"),
	"ace": LanguageModel(name="Achinese"),
	"acf": LanguageModel(name="St Lucian Creole French"),
	"ach": LanguageModel(name="Acoli"),
	"ada": LanguageModel(name="Adangme"),
	"adh": LanguageModel(name="Adhola"),
	"ady": LanguageModel(name="Adyghe"),
	"af": LanguageModel(name="Afrikaans"),
	"agr": LanguageModel(name="Aguaruna"),
	"ahk": LanguageModel(name="Akha"),
	"ak": LanguageModel(name="Twi"),
	"akb": LanguageModel(name="Batak Angkola"),
	"alt": LanguageModel(name="S. Altai"),
	"alz": LanguageModel(name="Alur"),
	"am": LanguageModel(name="Amharic"),
	"amu": LanguageModel(name="Guerrero Amuzgo"),
	"ang": LanguageModel(name="Old English"),
	"ann": LanguageModel(name="Obolo"),
	"ape": LanguageModel(name="Bukiyip"),
	"ar": LanguageModel(name="اَلْعَرَبِيَّةُ", metadata=LanguageMetadata(rtl=True)),
	"arn": LanguageModel(name="Mapudungun"),
	"ar_TN": LanguageModel(name="العربية (تونس)", metadata=LanguageMetadata(rtl=True)),
	"as": LanguageModel(name="Assamese"),
	"av": LanguageModel(name="Avar"),
	"awa": LanguageModel(name="Awadhi"),
	"ay": LanguageModel(name="Aymara"),
	"az": LanguageModel(name="Azerbaijani"),
	"ba": LanguageModel(name="Bashkir"),
	"ban": LanguageModel(name="Balinese"),
	"bas": LanguageModel(name="Basa (Cameroon)"),
	"bbc": LanguageModel(name="Batak Toba"),
	"bci": LanguageModel(name="Baoulé"),
	"be": LanguageModel(name="Belarusian"),
	"ber": LanguageModel(name="Tamazight (Tfng)"),
	"bew": LanguageModel(name="Betawi"),
	"bg": LanguageModel(name="Bulgarian"),
	"bgp": LanguageModel(name="E. Baluchi"),
	"bgz": LanguageModel(name="Banggai"),
	"bho": LanguageModel(name="Bhojpuri"),
	"bi": LanguageModel(name="Bislama"),
	"bik": LanguageModel(name="Central Bikol"),
	"bim": LanguageModel(name="Bimoba"),
	"bjj": LanguageModel(name="Kanauji"),
	"bm": LanguageModel(name="Bambara"),
	"bn": LanguageModel(name="Bengali"),
	"bo": LanguageModel(name="Tibetan"),
	"bqc": LanguageModel(name="Boko (Benin)"),
	"br": LanguageModel(name="Breton"),
	"bru": LanguageModel(name="E. Bru"),
	"brx": LanguageModel(name="Bodo (India)"),
	"bs": LanguageModel(name="Bosnian"),
	"bts": LanguageModel(name="Batak Simalungun"),
	"btx": LanguageModel(name="Batak Karo"),
	"bua": LanguageModel(name="Buryat"),
	"bum": LanguageModel(name="Bulu"),
	"bus": LanguageModel(name="Bokobaru"),
	"bzj": LanguageModel(name="Belize Kriol English"),
	"ca": LanguageModel(name="Català"),
	"cab": LanguageModel(name="Garifuna"),
	"cac": LanguageModel(name="Chuj"),
	"cak": LanguageModel(name="Kaqchikel"),
	"cbk": LanguageModel(name="Chavacano"),
	"cce": LanguageModel(name="Chopi"),
	"ce": LanguageModel(name="Chechen"),
	"ceb": LanguageModel(name="Cebuano"),
	"cfm": LanguageModel(name="Falam Chin"),
	"ch": LanguageModel(name="Chamorro"),
	"chk": LanguageModel(name="Chuukese"),
	"chm": LanguageModel(name="Meadow Mari"),
	"chr": LanguageModel(name="Cherokee"),
	"cjk": LanguageModel(name="Chokwe"),
	"ckb": LanguageModel(name="Kurdish (Sorani)"),
	"cnh": LanguageModel(name="Hakha Chin"),
	"cni": LanguageModel(name="Asháninka"),
	"co": LanguageModel(name="Corsican"),
	"crh": LanguageModel(name="Crimean Tatar"),
	"crs": LanguageModel(name="Seselwa Creole French"),
	"cs": LanguageModel(name="Čeština"),
	"ctu": LanguageModel(name="Chol"),
	"cuk": LanguageModel(name="San Blas Kuna"),
	"cv": LanguageModel(name="Chuvash"),
	"cy": LanguageModel(name="Welsh"),
	"da": LanguageModel(name="Danish"),
	"de": LanguageModel(name="Deutsch"),
	"din": LanguageModel(name="Dinka"),
	"dje": LanguageModel(name="Zarma"),
	"djk": LanguageModel(name="E. Maroon Creole"),
	"dov": LanguageModel(name="Dombe"),
	"dtp": LanguageModel(name="Kadazan Dusun"),
	"dv": LanguageModel(name="Dhivehi"),
	"dwr": LanguageModel(name="Dawro"),
	"dyu": LanguageModel(name="Dyula"),
	"dz": LanguageModel(name="Dzongkha"),
	"ee": LanguageModel(name="Ewe"),
	"el": LanguageModel(name="Greek"),
	"emp": LanguageModel(name="N. Emberá"),
	"en": LanguageModel(name="English"),
	"enq": LanguageModel(name="Enga"),
	"eo": LanguageModel(name="Esperanto"),
	"es": LanguageModel(name="Español"),
	"et": LanguageModel(name="Estonian"),
	"eu": LanguageModel(name="Basque"),
	"fa": LanguageModel(name="فارسی", metadata=LanguageMetadata(rtl=True)),
	"ff": LanguageModel(name="Fulfulde"),
	"ffm": LanguageModel(name="Maasina Fulfulde"),
	"fi": LanguageModel(name="Finnish"),
	"fil": LanguageModel(name="Filipino"),
	"fip": LanguageModel(name="Fipa"),
	"fj": LanguageModel(name="Fijian"),
	"fo": LanguageModel(name="Faroese"),
	"fon": LanguageModel(name="Fon"),
	"fr": LanguageModel(name="Français"),
	"frp": LanguageModel(name="Arpitan"),
	"fy": LanguageModel(name="W. Frisian"),
	"ga": LanguageModel(name="Irish"),
	"gag": LanguageModel(name="Gagauz"),
	"gbm": LanguageModel(name="Garhwali"),
	"gd": LanguageModel(name="Scottish Gaelic"),
	"gil": LanguageModel(name="Gilbertese"),
	"gl": LanguageModel(name="Galician"),
	"gn": LanguageModel(name="Guarani"),
	"gof": LanguageModel(name="Gofa"),
	"gom": LanguageModel(name="Goan Konkani"),
	"gor": LanguageModel(name="Gorontalo"),
	"grc": LanguageModel(name="Ancient Greek"),
	"gsw": LanguageModel(name="Swiss German"),
	"gu": LanguageModel(name="Gujarati"),
	"gub": LanguageModel(name="Guajajára"),
	"guc": LanguageModel(name="Wayuu"),
	"guh": LanguageModel(name="Guahibo"),
	"gui": LanguageModel(name="E. Bolivian Guaraní"),
	"gv": LanguageModel(name="Manx"),
	"gvl": LanguageModel(name="Gulay"),
	"gym": LanguageModel(name="Ngäbere"),
	"gyn": LanguageModel(name="Guyanese Creole English"),
	"ha": LanguageModel(name="Hausa"),
	"haw": LanguageModel(name="Hawaiian"),
	"he": LanguageModel(name="Hebrew", metadata=LanguageMetadata(rtl=True)),
	"hi": LanguageModel(name="हिंदी"),
	"hif": LanguageModel(name="Fiji Hindi"),
	"hil": LanguageModel(name="Hiligaynon"),
	"hmn": LanguageModel(name="Hmong"),
	"hne": LanguageModel(name="Chhattisgarhi"),
	"ho": LanguageModel(name="Hiri Motu"),
	"hr": LanguageModel(name="Croatian"),
	"ht": LanguageModel(name="Haitian Creole"),
	"hu": LanguageModel(name="Hungarian"),
	"hui": LanguageModel(name="Huli"),
	"hus": LanguageModel(name="Huastec"),
	"hvn": LanguageModel(name="Sabu"),
	"hy": LanguageModel(name="Armenian"),
	"iba": LanguageModel(name="Iban"),
	"ibb": LanguageModel(name="Ibibio"),
	"id": LanguageModel(name="Indonesian"),
	"ify": LanguageModel(name="Keley-I Kallahan"),
	"ig": LanguageModel(name="Igbo"),
	"ilo": LanguageModel(name="Ilocano"),
	"inb": LanguageModel(name="Inga"),
	"is": LanguageModel(name="Icelandic"),
	"iso": LanguageModel(name="Isoko"),
	"it": LanguageModel(name="Italiano"),
	"iu": LanguageModel(name="Inuktitut"),
	"ium": LanguageModel(name="Iu Mien"),
	"izz": LanguageModel(name="Izii"),
	"ja": LanguageModel(name="日本語", metadata=LanguageMetadata(separator="")),
	"jac": LanguageModel(name="Popti'"),
	"jam": LanguageModel(name="Jamaican Creole English"),
	"jax": LanguageModel(name="Jambi Malay"),
	"jiv": LanguageModel(name="Shuar"),
	"jv": LanguageModel(name="Javanese"),
	"jvn": LanguageModel(name="Caribbean Javanese"),
	"ka": LanguageModel(name="Georgian"),
	"kaa": LanguageModel(name="Kara-Kalpak"),
	"kaa-Latn": LanguageModel(name="Kara-Kalpak (Latn)"),
	"kac": LanguageModel(name="Kachin"),
	"kbd": LanguageModel(name="Kabardian"),
	"kbp": LanguageModel(name="Kabiyè"),
	"kek": LanguageModel(name="Kekchí"),
	"kg": LanguageModel(name="Kongo"),
	"kha": LanguageModel(name="Khasi"),
	"kj": LanguageModel(name="Kuanyama"),
	"kjg": LanguageModel(name="Khmu"),
	"kjh": LanguageModel(name="Khakas"),
	"kk": LanguageModel(name="қазақ"),
	"kl": LanguageModel(name="Kalaallisut"),
	"km": LanguageModel(name="Khmer"),
	"kmb": LanguageModel(name="Kimbundu"),
	"kn": LanguageModel(name="Kannada"),
	"knj": LanguageModel(name="W. Kanjobal"),
	"ko": LanguageModel(name="한국인"),
	"koi": LanguageModel(name="Komi-Permyak"),
	"kos": LanguageModel(name="Kosraean"),
	"krc": LanguageModel(name="Karachay-Balkar"),
	"kri": LanguageModel(name="Krio"),
	"krj": LanguageModel(name="Kinaray-A"),
	"ks": LanguageModel(name="Kashmiri"),
	"ksd": LanguageModel(name="Kuanua"),
	"ksw": LanguageModel(name="S'gaw Karen"),
	"ktu": LanguageModel(name="Kituba (DRC)"),
	"ku": LanguageModel(name="Kurdish (Kurmanji)"),
	"kum": LanguageModel(name="Kumyk"),
	"kv": LanguageModel(name="Komi"),
	"kw": LanguageModel(name="Cornish"),
	"kwi": LanguageModel(name="Awa-Cuaiquer"),
	"ky": LanguageModel(name="Kyrghyz"),
	"la": LanguageModel(name="Latin"),
	"laj": LanguageModel(name="Lango (Uganda)"),
	"lb": LanguageModel(name="Luxembourgish"),
	"lg": LanguageModel(name="Luganda"),
	"lhu": LanguageModel(name="Lahu"),
	"ln": LanguageModel(name="Lingala"),
	"lo": LanguageModel(name="Lao"),
	"lrc": LanguageModel(name="N. Luri"),
	"lt": LanguageModel(name="Lithuanian"),
	"ltg": LanguageModel(name="Latgalian"),
	"lu": LanguageModel(name="Luba-Katanga"),
	"lus": LanguageModel(name="Mizo"),
	"luz": LanguageModel(name="S. Luri"),
	"lv": LanguageModel(name="Latvian"),
	"mad": LanguageModel(name="Madurese"),
	"mag": LanguageModel(name="Magahi"),
	"mai": LanguageModel(name="Maithili"),
	"mak": LanguageModel(name="Makasar"),
	"mam": LanguageModel(name="Mam"),
	"mas": LanguageModel(name="Masai"),
	"maz": LanguageModel(name="Central Mazahua"),
	"mbt": LanguageModel(name="Matigsalug Manobo"),
	"mdf": LanguageModel(name="Moksha"),
	"mel": LanguageModel(name="Central Melanau"),
	"meo": LanguageModel(name="Kedah Malay"),
	"meu": LanguageModel(name="Motu"),
	"mey": LanguageModel(name="Hassaniyya"),
	"mfe": LanguageModel(name="Morisien"),
	"mg": LanguageModel(name="Malagasy"),
	"mgh": LanguageModel(name="Makhuwa-Meetto"),
	"mh": LanguageModel(name="Marshallese"),
	"mi": LanguageModel(name="Maori"),
	"min": LanguageModel(name="Minangkabau"),
	"miq": LanguageModel(name="Mískito"),
	"mk": LanguageModel(name="Macedonian"),
	"mkn": LanguageModel(name="Kupang Malay"),
	"ml": LanguageModel(name="Malayalam"),
	"mn": LanguageModel(name="Mongolian"),
	"mni": LanguageModel(name="Meiteilon (Manipuri)"),
	"mnw": LanguageModel(name="Mon"),
	"mps": LanguageModel(name="Dadibi"),
	"mqy": LanguageModel(name="Manggarai"),
	"mr": LanguageModel(name="Marathi"),
	"mrj": LanguageModel(name="Hill Mari"),
	"mrw": LanguageModel(name="Maranao"),
	"ms": LanguageModel(name="Malay"),
	"msb": LanguageModel(name="Masbatenyo"),
	"msi": LanguageModel(name="Sabah Malay"),
	"msm": LanguageModel(name="Agusan Manobo"),
	"mt": LanguageModel(name="Maltese"),
	"mtr": LanguageModel(name="Mewari"),
	"my": LanguageModel(name="Myanmar (Burmese)"),
	"myv": LanguageModel(name="Erzya"),
	"ne": LanguageModel(name="Nepali"),
	"new": LanguageModel(name="Newari"),
	"ngu": LanguageModel(name="Guerrero Nahuatl"),
	"nhe": LanguageModel(name="E. Huasteca Nahuatl"),
	"nia": LanguageModel(name="Nias"),
	"nij": LanguageModel(name="Ngaju"),
	"niq": LanguageModel(name="Nandi"),
	"nl": LanguageModel(name="Nederlands"),
	"nnb": LanguageModel(name="Nande"),
	"no": LanguageModel(name="Norwegian"),
	"noa": LanguageModel(name="Woun Meu"),
	"noe": LanguageModel(name="Nimadi"),
	"nog": LanguageModel(name="Nogai"),
	"nr": LanguageModel(name="South Ndebele"),
	"nso": LanguageModel(name="Sepedi"),
	"nut": LanguageModel(name="Nung (Viet Nam)"),
	"nv": LanguageModel(name="Navajo"),
	"ny": LanguageModel(name="Chichewa"),
	"nyu": LanguageModel(name="Nyungwe"),
	"nzi": LanguageModel(name="Nzima"),
	"oc": LanguageModel(name="Occitan"),
	"oj": LanguageModel(name="Ojibwa"),
	"om": LanguageModel(name="Oromo"),
	"or": LanguageModel(name="Odia (Oriya)"),
	"os": LanguageModel(name="Ossetian"),
	"otq": LanguageModel(name="Querétaro Otomi"),
	"pa": LanguageModel(name="Punjabi"),
	"pag": LanguageModel(name="Pangasinan"),
	"pam": LanguageModel(name="Pampanga"),
	"pap": LanguageModel(name="Papiamento"),
	"pau": LanguageModel(name="Palauan"),
	"pck": LanguageModel(name="Paite Chin"),
	"pis": LanguageModel(name="Pijin"),
	"pl": LanguageModel(name="Polski"),
	"pon": LanguageModel(name="Pohnpeian"),
	"ppk": LanguageModel(name="Uma"),
	"prk": LanguageModel(name="Parauk"),
	"ps": LanguageModel(name="Pashto"),
	"pt": LanguageModel(name="Português"),
	"qu": LanguageModel(name="Quechua"),
	"qub": LanguageModel(name="Huallaga Huánuco Quechua"),
	"qug": LanguageModel(name="Chimborazo Highland Quichua"),
	"raj": LanguageModel(name="Rajasthani"),
	"rap": LanguageModel(name="Rapanui"),
	"rar": LanguageModel(name="Rarotongan"),
	"rm": LanguageModel(name="Romansh"),
	"rn": LanguageModel(name="Rundi"),
	"ro": LanguageModel(name="Romanian"),
	"roa": LanguageModel(name="Arpitan"),
	"rof": LanguageModel(name="Rombo"),
	"rom": LanguageModel(name="Romany"),
	"ru": LanguageModel(name="Русский"),
	"rue": LanguageModel(name="Rusyn"),
	"rw": LanguageModel(name="Kinyarwanda"),
	"sa": LanguageModel(name="Sanskrit"),
	"sah": LanguageModel(name="Sakha"),
	"sam": LanguageModel(name="Samaritan Aramaic"),
	"saq": LanguageModel(name="Samburu"),
	"sat": LanguageModel(name="Santali"),
	"sbp": LanguageModel(name="Sangu"),
	"sc": LanguageModel(name="Sardinian"),
	"sck": LanguageModel(name="Sadri"),
	"sd": LanguageModel(name="Sindhi"),
	"se": LanguageModel(name="N. Sami"),
	"see": LanguageModel(name="Seneca"),
	"seh": LanguageModel(name="Sena"),
	"ses": LanguageModel(name="Koyraboro Senni"),
	"sg": LanguageModel(name="Sango"),
	"shn": LanguageModel(name="Shan"),
	"si": LanguageModel(name="Sinhala"),
	"sid": LanguageModel(name="Sidamo"),
	"sk": LanguageModel(name="Slovak"),
	"sl": LanguageModel(name="Slovenian"),
	"sm": LanguageModel(name="Samoan"),
	"sma": LanguageModel(name="S. Sami"),
	"smj": LanguageModel(name="Lule Sami"),
	"smn": LanguageModel(name="Inari Sami"),
	"sn": LanguageModel(name="Shona"),
	"so": LanguageModel(name="Somali"),
	"sq": LanguageModel(name="Albanian"),
	"sr": LanguageModel(name="Serbian"),
	"ss": LanguageModel(name="Swati"),
	"st": LanguageModel(name="S. Sotho"),
	"su": LanguageModel(name="Sundanese"),
	"suk": LanguageModel(name="Sukuma"),
	"sv": LanguageModel(name="Swedish"),
	"sw": LanguageModel(name="Swahili"),
	"swb": LanguageModel(name="Comorian"),
	"syc": LanguageModel(name="Classical Syriac"),
	"ta": LanguageModel(name="Tamil"),
	"tab": LanguageModel(name="Tabassaran"),
	"te": LanguageModel(name="తెలుగు"),
	"tem": LanguageModel(name="Timne"),
	"teo": LanguageModel(name="Teso"),
	"tet": LanguageModel(name="Tetum"),
	"tg": LanguageModel(name="тоҷикӣ"),
	"th": LanguageModel(name="Thai"),
	"ti": LanguageModel(name="Tigrinya"),
	"tig": LanguageModel(name="Tigre"),
	"tk": LanguageModel(name="Turkmen"),
	"tkl": LanguageModel(name="Tokelau"),
	"tl": LanguageModel(name="Tagalog"),
	"tlh": LanguageModel(name="Klingon"),
	"tli": LanguageModel(name="Tlingit"),
	"tmh": LanguageModel(name="Tamashek"),
	"tn": LanguageModel(name="Tswana"),
	"to": LanguageModel(name="Tongan"),
	"tog": LanguageModel(name="Tonga (Nyasa)"),
	"tpi": LanguageModel(name="Tok Pisin"),
	"tr": LanguageModel(name="Türkçe"),
	"tru": LanguageModel(name="Turoyo"),
	"ts": LanguageModel(name="Tsonga"),
	"tt": LanguageModel(name="Tatar"),
	"tum": LanguageModel(name="Tumbuka"),
	"tvl": LanguageModel(name="Tuvalu"),
	"tw": LanguageModel(name="Twi"),
	"ty": LanguageModel(name="Tahitian"),
	"tyv": LanguageModel(name="Tuvinian"),
	"tzm": LanguageModel(name="Central Atlas Tamazight"),
	"udm": LanguageModel(name="Udmurt"),
	"ug": LanguageModel(name="Uyghur"),
	"uk": LanguageModel(name="українська"),
	"umb": LanguageModel(name="Umbundu"),
	"und": LanguageModel(name="Undetermined"),
	"ur": LanguageModel(name="Urdu"),
	"uz": LanguageModel(name="o'zbek"),
	"vai": LanguageModel(name="Vai"),
	"ve": LanguageModel(name="Venda"),
	"vi": LanguageModel(name="Tiếng Việt"),
	"vls": LanguageModel(name="West Flemish"),
	"vo": LanguageModel(name="Volapük"),
	"vot": LanguageModel(name="Votic"),
	"wa": LanguageModel(name="Walloon"),
	"wak": LanguageModel(name="Wakashan languages"),
	"wal": LanguageModel(name="Wolaytta"),
	"war": LanguageModel(name="Waray"),
	"was": LanguageModel(name="Washo"),
	"wo": LanguageModel(name="Wolof"),
	"xal": LanguageModel(name="Kalmyk"),
	"xh": LanguageModel(name="Xhosa"),
	"xog": LanguageModel(name="Soga"),
	"yao": LanguageModel(name="Yao"),
	"yap": LanguageModel(name="Yapese"),
	"yav": LanguageModel(name="Yangben"),
	"yi": LanguageModel(name="Yiddish", metadata=LanguageMetadata(rtl=True)),
	"yo": LanguageModel(name="Yoruba"),
	"yrl": LanguageModel(name="Nheengatu"),
	"yue": LanguageModel(name="Cantonese"),
	"za": LanguageModel(name="Zhuang"),
	"zap": LanguageModel(name="Zapotec"),
	"zbl": LanguageModel(name="Blissymbols"),
	"zen": LanguageModel(name="Zenaga"),
	"zh": LanguageModel(name="中国", metadata=LanguageMetadata(separator="")),
	"zu": LanguageModel(name="Zulu"),
	"zun": LanguageModel(name="Zuni"),
}


VOSK_SUPPORTED_LANGUAGE_MAP = {lang_id: LANGUAGE_MAP[lang_id] for lang_id in MODELS_LIST}
