# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization
#
# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Docker build and publish

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    # Only allowed to be run on nextcloud-releases repositories
    if: ${{ github.repository_owner == 'nextcloud-releases' }}

    steps:
      - name: Checkout app
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Get app ID
        run: |
          echo "APP_ID=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Get app version
        id: appinfo
        uses: skjnldsv/xpath-action@f5b036e9d973f42c86324833fd00be90665fbf77 # v1.0.0
        with:
          filename: appinfo/info.xml
          expression: "/info/version/text()"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          cache-image: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          cache-binary: false

      - name: Login to GitHub Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get HEAD git commit timestamp
        run: echo "HEAD_TIMESTAMP=$(git log -1 --pretty=%ct)" >> $GITHUB_ENV

      - name: Build and push the CPU image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        env:
          SOURCE_DATE_EPOCH: ${{ env.HEAD_TIMESTAMP }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/nextcloud-releases/${{ env.APP_ID }}:latest
            ghcr.io/nextcloud-releases/${{ env.APP_ID }}:${{ fromJson(steps.appinfo.outputs.result).version }}
          build-args: |
            HAVE_CUDA=0
            KALDI_MKL=1
            RT_IMAGE=ubuntu:22.04
          no-cache: true

      - name: Build and push the CUDA image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        env:
          SOURCE_DATE_EPOCH: ${{ env.HEAD_TIMESTAMP }}
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/nextcloud-releases/${{ env.APP_ID }}:latest-cuda
            ghcr.io/nextcloud-releases/${{ env.APP_ID }}:${{ fromJson(steps.appinfo.outputs.result).version }}-cuda
          build-args: |
            HAVE_CUDA=1
            KALDI_MKL=0
            RT_IMAGE=nvidia/cuda:12.4.1-devel-ubuntu22.04
          no-cache: true
